# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 594c5125870fd3c317c953405a1a27d8485a1e6db87518b24b7b371c993d8218817a7ad60c49b8f9740f399b74ce95bee111ec09aabeccf669f4cf81dc9c84c1

test:
  secret_key_base: 49b7b60807f30b4e581230b1cb1c14fcd5bc932a2f0decae96de5cd7af409a209de58a0f4377a0fcf2a202f17616a5dacb497458cd701f1fe6c25ef15b3010be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
